version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:7.0-alpine
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - 6379:6379

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl